project:
  type: website
  output-dir: docs
  render:
    - eda/eda_recipe_recommendations.ipynb
    - eda/eda_ingredients_extraction.ipynb

website:

  navbar:
    background: "#497D74"
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/pdgarden/recipe-recommender-system

  sidebar:
    style: "floating"
    search: false
    contents:
      - text: "Recipe recommendation"
        href: eda/eda_recipe_recommendations.ipynb
      - text : "Ingredients extraction"
        href: eda/eda_ingredients_extraction.ipynb

format:
  html:
    theme: flatly

